## Exposes the debuging port and runs node with the debuging command

version: '2.1'

services:
  ehealth:
    image: ehealth
    build: .
    env_file:
      - .env
    # environment:
    #   NODE_ENV: development
    ports:
      - 3001:3001
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js
